### PR TITLE
Spoiler rendering

### PR DESCRIPTION
**Pull request by derpondus**
### Description
Add Support for spoiler tags, as seen in discord: `||<not-empty>||`. 
Messages are scanned and found tags are replaced with a span, which hides the text by making it transparent and not selectable. 
There is a hover-'animation' and -popup indicating clickability, and on click the text-color reverts to its original, and the background becomes slightly lighter.  Another click hides the spoiler again.

### Design
- I put the call to `reattachCommentObserver()` directly into `checkAndInject()`
    - otherwise, it can be called in `checkAndUpdate()` and the `readystatechange` listener (I would also have to copy the `onRemoved()` function from my Tampermonkey script to wait for the actual element removal)
- I purposefully split the `renderFeatures()` and `replaceSpoilesWithHTML()` functions to allow additional features to be rendered if necessary (e.g. the timestamps or whatever 🤷)
- The pattern has changed from my initial message in the discord channel. It is now allowed to put spaces anywhere close to the `||` delimiters, as `|| ||` is also a valid spoiler in discord. (Initially, no spaces were allowed between the delimiter and the contained text)
- I am 60% certain that making `checkAndInject()` async was not strictly necessary, but it is probably good to keep the order of operations explicit 🤔

### Changelog
- add mutationObserver for the comment holder element
    - reattach it when comentario has been reset
    - wait for the reattachment process to be completed before continuing
- do spoiler rendering when comments change
    - spoiler syntax: `||<not-empty>||`
    - replaced with styled spans
    - with click listener for revealing the spoiler
- add some code comments
- add .idea Jetbrains-IDE config folder to gitignore

Greetings
PondusDev

### CODE REVIEW

**Comment by derpondus** [comment]
Notify me, if you want me to resolve the conflicts. 👍

**Comment by martian0x80** [comment]
hey @derpondus thanks for the first PR!
I know this is on me, but can you change the base branch to a corresponding branch with the same name? (`martian0x80:spoiler-render`). I should add a CONTRIBUTION.md lol

(Open a new PR if you can't change it, thankss)

**Comment by derpondus** [comment]
I done have the rights to create new branches in this repo, but if you create the branch I can edit the PR.

No worries 😄

**Comment by derpondus** [comment]
Aah, forgot the tag 😅 
@martian0x80

**Comment by martian0x80** [comment]
created a new branch

**Comment by derpondus** [comment]
done

**Comment by martian0x80** [comment]
everything looks alright now, will test and merge the pr soon

**Pull request merged**
